### ISSUE TITLE
change cookie statement to match privacy statement font

### ISSUE THREAD

**Issue by demeesterdev** [demeesterdev/demdev-groundyourself-theme#14]
# Summary of the new feature/enhancement

implement css to match the complianze cookie statement to the rest of the site
# Proposed technical implementation details (optional)

add the following code to `style.css`:
```css
#cmplz-document {
	max-width:inherit;
	text-align:left;
	font-size:16px;
}

#cmplz-document p,
#cmplz-document li,
#cmplz-document td {
	font-size:16px;
}

#cmplz-document h2, #cmplz-document h3 {
	border-bottom: none;
}
```
